# Generated by Django 5.2.4 on 2025-09-03 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_reconcilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('Amount', models.FloatField(default=0)),
                ('Remark', models.CharField(max_length=500, null=True)),
                ('Description', models.TextField(null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='audit2.bank_name')),
            ],
        ),
        migrations.CreateModel(
            name='BankBalanceUplooad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='BankBalance')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='baluploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankReconcilationeUplooad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='BankReconcilation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconuploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('Bank_balance', models.FloatField()),
                ('Tally_balance', models.FloatField()),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='writer', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='audit2.bank_name')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bank', 'reporting_date'), name='oned')],
            },
        ),
    ]
