# Generated by Django 5.2.4 on 2025-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_reconcilation',
            name='appearance',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
