# Generated by Django 5.2.4 on 2025-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit2', '0003_bank_reconcilation_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_reconcilation',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
