# Generated by Django 5.2.4 on 2025-07-27 21:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callDateTrack', models.DateField(auto_now_add=True)),
                ('callDate', models.DateField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='businessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='customerCat',
            fields=[
                ('cust_channel', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='regionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hmd', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='areaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('businessManager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.businessmanager')),
            ],
        ),
        migrations.AddField(
            model_name='businessmanager',
            name='regionManager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.regionmanager'),
        ),
        migrations.CreateModel(
            name='rep',
            fields=[
                ('salesman_name', models.CharField(max_length=500)),
                ('salesman_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('areaManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.areamanager')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('cust_code', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('cust_location', models.CharField(max_length=5000)),
                ('cust_latitude', models.CharField(max_length=500)),
                ('cust_longitude', models.CharField(max_length=500)),
                ('cust_state', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.customercat')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.rep')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_code', models.CharField(max_length=500)),
                ('createdate', models.DateField()),
                ('visit_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('activity_product', models.CharField(max_length=500)),
                ('activity_comment', models.CharField(max_length=5000)),
                ('contactname', models.CharField(max_length=500)),
                ('rank_desc', models.CharField(max_length=500)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('joint_work_descn', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.customer')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.rep')),
            ],
        ),
    ]
