# Generated by Django 5.2.4 on 2025-08-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failcalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_channel',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_channels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.customercat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reps', to='fieldsales.rep'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='areaManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='areamgrs', to='fieldsales.areamanager'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='a_code',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='activity_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='activity_product',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='contactname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='createdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.customer'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='distance',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='joint_work_descn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='latitude',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longitude',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rank_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repss', to='fieldsales.rep'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(null=True),
        ),
    ]
