# Generated by Django 5.2.4 on 2025-07-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.customercat'),
        ),
    ]
