# Generated by Django 5.2.4 on 2025-08-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0002_failcalls_remove_customer_cust_channel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Failcalls',
        ),
    ]
