# Generated by Django 5.2.4 on 2025-07-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0002_alter_customer_cust_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_channel',
            new_name='cust_channels',
        ),
    ]
