# Generated by Django 5.2.4 on 2025-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0003_delete_failcalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failcalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failDate', models.DateField()),
            ],
        ),
    ]
