# Generated by Django 5.2.4 on 2025-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0003_rename_cust_channel_customer_cust_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
