# Generated by Django 5.2.4 on 2025-07-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0004_customer_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.AlterField(
            model_name='visit',
            name='a_code',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
