# Generated by Django 5.2.4 on 2025-07-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0005_remove_visit_id_alter_visit_a_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_time',
        ),
    ]
