# Generated by Django 5.2.4 on 2025-07-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0006_remove_visit_end_time_remove_visit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
