# Generated by Django 5.2.4 on 2025-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0007_alter_visit_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
