# Generated by Django 5.2.4 on 2025-07-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0008_alter_visit_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='activity_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='activity_product',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='contactname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='createdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.customer'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='joint_work_descn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='latitude',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longitude',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rank_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fieldsales.rep'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(null=True),
        ),
    ]
