# Generated by Django 5.2.4 on 2025-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsales', '0009_alter_visit_activity_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='distance',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
