# Generated by Django 5.2.4 on 2025-08-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, unique=True)),
                ('Allias', models.CharField(max_length=1000)),
                ('Parent', models.CharField(max_length=1000)),
                ('Credit_limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, unique=True)),
                ('Sales', models.FloatField()),
                ('collection', models.FloatField()),
                ('Balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('Uom', models.CharField(max_length=50)),
                ('QPC', models.DecimalField(decimal_places=5, max_digits=5)),
                ('QPC2', models.FloatField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('price2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='account')),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='capacityUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='capacity')),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Name', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500, null=True)),
                ('Allias', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Address', models.CharField(max_length=1000, null=True)),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales2.group')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales2.region')),
            ],
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales2.area')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales2.rep'),
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='sales')),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNum', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=500)),
                ('units', models.IntegerField()),
                ('ctns', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('temp_region', models.CharField(max_length=500)),
                ('temp_margin', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temp_margin2', models.FloatField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='sales2.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='sales2.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('VoucherNum', 'product'), name='vouchervsproduct')],
            },
        ),
    ]
