# Generated by Django 5.2.4 on 2025-08-23 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, unique=True)),
                ('Allias', models.CharField(max_length=1000)),
                ('Parent', models.CharField(max_length=1000)),
                ('Credit_limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='account')),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, unique=True)),
                ('Sales', models.FloatField()),
                ('collection', models.FloatField()),
                ('Balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='capacityUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='capacity')),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='Date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='VoucherNum',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='salesrecords',
            constraint=models.UniqueConstraint(fields=('VoucherNum', 'product'), name='vouchervsproduct'),
        ),
        migrations.AddField(
            model_name='accountsupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacityupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
