# Generated by Django 5.2.4 on 2025-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesrecords',
            constraint=models.UniqueConstraint(fields=('VoucherNum', 'product'), name='vouchervsproduct'),
        ),
    ]
