# Generated by Django 5.2.4 on 2025-08-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='customer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='product',
            field=models.CharField(max_length=500),
        ),
    ]
