# Generated by Django 5.2.4 on 2025-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0002_salesrecords_vouchervsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='VoucherNum',
            field=models.CharField(max_length=50),
        ),
    ]
