# Generated by Django 5.2.4 on 2025-08-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0002_alter_salesrecords_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='Date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
