# Generated by Django 5.2.4 on 2025-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0003_alter_salesrecords_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecords2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNum', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=500, null=True)),
                ('units', models.IntegerField()),
                ('ctns', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('temp_region', models.CharField(max_length=500)),
                ('customer', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('temp_margin', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temp_margin2', models.FloatField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('VoucherNum', 'product'), name='vouchervsproduct2')],
            },
        ),
    ]
