# Generated by Django 5.2.4 on 2025-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0004_salesrecords2'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='Allias',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
