# Generated by Django 5.2.4 on 2025-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0004_capacity_capacityupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='Name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
