# Generated by Django 5.2.4 on 2025-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0005_capacity_allias'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecords',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesrecords',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
