# Generated by Django 5.2.4 on 2025-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0005_alter_capacity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True),
        ),
    ]
