# Generated by Django 5.2.4 on 2025-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0007_salesrecords2_month_salesrecords2_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecords2',
            name='company',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
