# Generated by Django 5.2.4 on 2025-08-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0007_capacity_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacity',
            name='company',
        ),
        migrations.AddField(
            model_name='capacityupload',
            name='company',
            field=models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True),
        ),
    ]
