# Generated by Django 5.2.4 on 2025-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0008_salesrecords2_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('WEST', 'WEST'), ('EAST', 'EAST'), ('LAGOS', 'LAGOS'), ('NORTH', 'NORTH'), ('CONSUMER', 'CONSUMER')], max_length=500, null=True)),
                ('email', models.EmailField(max_length=1254)),
            ],
        ),
    ]
