# Generated by Django 5.2.4 on 2025-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0009_salesstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstructure',
            name='region',
            field=models.CharField(choices=[('WEST', 'WEST'), ('EAST', 'EAST'), ('LAGOS', 'LAGOS'), ('NORTH', 'NORTH'), ('CONSUMER', 'CONSUMER'), ('OTHERS', 'OTHERS'), ('DISTRIBUTORS', 'DISTRIBUTORS'), ('STALLION', 'STALLION')], max_length=500, null=True),
        ),
    ]
