# Generated by Django 5.2.4 on 2025-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0010_alter_salesstructure_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacityupload',
            name='upload_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='upload_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
