# Generated by Django 5.2.4 on 2025-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0010_alter_accountsupload_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Allias',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Parent',
            field=models.CharField(max_length=1000),
        ),
    ]
