# Generated by Django 5.2.4 on 2025-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0011_alter_accounts_allias_alter_accounts_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsupload',
            name='file',
            field=models.FileField(upload_to='account'),
        ),
        migrations.AlterField(
            model_name='capacityupload',
            name='file',
            field=models.FileField(upload_to='capacity'),
        ),
    ]
