# Generated by Django 5.2.4 on 2025-08-30 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('bank', models.CharField(max_length=500)),
                ('Bank_balance', models.FloatField()),
                ('Tally_balance', models.FloatField()),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(choices=[('GREENLIFE', 'GREENLIFE'), ('GREENFALCON', 'GREENFALCON')], max_length=500, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_reconcilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('Bank_balance', models.FloatField()),
                ('Tally_balance', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='audit.bank_name')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
