# Generated by Django 5.2.4 on 2025-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_bank_balance_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_reconcilation',
            name='Status',
            field=models.CharField(default='Uncleared', max_length=50),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='appearance',
            field=models.IntegerField(default=1),
        ),
    ]
