# Generated by Django 5.2.4 on 2025-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_bank_reconcilation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_reconcilation',
            name='Bank_balance',
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='Remark',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
