# Generated by Django 5.2.4 on 2025-08-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_bank_reconcilation_bank_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_reconcilation',
            name='Tally_balance',
        ),
    ]
