# Generated by Django 5.2.4 on 2025-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_bank_reconcilation_cleared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_reconcilation',
            name='cleared_on',
            field=models.DateField(null=True),
        ),
    ]
