# Generated by Django 5.2.4 on 2025-08-31 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_bank_reconcilation_cleared_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_reconcilation',
            name='cleared_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bank_reconcilation',
            constraint=models.UniqueConstraint(fields=('bank', 'Description', 'Remark', 'Amount'), name='onedata'),
        ),
    ]
