# Generated by Django 5.2.4 on 2025-09-03 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_bank_reconcilation_cleared_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalanceUplooad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='BankBalance')),
            ],
        ),
        migrations.CreateModel(
            name='BankReconcilationeUplooad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='BankReconcilation')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bank_reconcilation',
            name='onedata',
        ),
        migrations.AddConstraint(
            model_name='bank_balance',
            constraint=models.UniqueConstraint(fields=('bank', 'reporting_date'), name='onedatas'),
        ),
        migrations.AddConstraint(
            model_name='bank_reconcilation',
            constraint=models.UniqueConstraint(fields=('bank', 'reporting_date', 'Remark', 'Amount', 'appearance'), name='onedata'),
        ),
        migrations.AddField(
            model_name='bankbalanceuplooad',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconcilationeuplooad',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
