# Generated by Django 5.2.4 on 2025-09-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_bankbalanceuplooad_bankreconcilationeuplooad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbalanceuplooad',
            options={'managed': False},
        ),
    ]
