# Generated by Django 5.2.4 on 2025-09-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_alter_bankbalanceuplooad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbalanceuplooad',
            options={},
        ),
    ]
