# Generated by Django 5.2.4 on 2025-09-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_alter_bankbalanceuplooad_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bank_balance',
            name='onedatas',
        ),
    ]
