# Generated by Django 5.2.4 on 2025-09-03 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_remove_bank_balance_onedatas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bank_balance',
            constraint=models.UniqueConstraint(fields=('bank', 'reporting_date'), name='onedatas'),
        ),
    ]
