# Generated by Django 5.2.4 on 2025-09-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_bank_balance_onedatas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_name',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='bank_reconcilation',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bank_reconcilation',
            name='cleared_by',
        ),
        migrations.RemoveField(
            model_name='bank_reconcilation',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='bankbalanceuplooad',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='bankreconcilationeuplooad',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='bank_balance',
        ),
        migrations.DeleteModel(
            name='bank_name',
        ),
        migrations.DeleteModel(
            name='bank_reconcilation',
        ),
        migrations.DeleteModel(
            name='BankBalanceUplooad',
        ),
        migrations.DeleteModel(
            name='BankReconcilationeUplooad',
        ),
    ]
